#!/usr/bin/env node
// Plan status board for docs/plans/svelte-rewrite.
//
//   node scripts/harness/plan-status.mjs            -> prints the board summary per epic
//   node scripts/harness/plan-status.mjs next       -> prints the next open tasks whose dependencies are done
//   node scripts/harness/plan-status.mjs E4         -> prints every task of one epic with its state
//   node scripts/harness/plan-status.mjs --sync     -> regenerates STATUS.md from the epic files, keeping ticks and hashes
//   node scripts/harness/plan-status.mjs --done E4-S1-T1 <hash>   -> ticks a task in STATUS.md
//   node scripts/harness/plan-status.mjs --blocked E4-S1-T1 "why" -> marks a task blocked
//
// Tasks are the `#### <ID> <title>` headings in the epic files; `Depends:` lines list prerequisites.
// A dependency may be a task id (E1-S2-T1), a story id (E1-S2, meaning every task of it) or an epic id (E1 / B0).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..', '..');
const planDir = path.join(root, 'docs', 'plans', 'svelte-rewrite');
const statusFile = path.join(planDir, 'STATUS.md');

const TASK_RE = /^####\s+((?:E|B)\d+-S\d+-T\d+)\s+(.*)$/;
const STORY_RE = /^###\s+((?:E|B)\d+-S\d+)\s+(.*)$/;
const EPIC_RE = /^#\s+((?:E|B)\d+)\s*[·:-]\s*(.*)$/;

function readEpics() {
  const files = fs.readdirSync(planDir).filter((f) => /^(E|B)\d+-.*\.md$/.test(f)).sort(sortByEpic);
  const epics = [];
  for (const file of files) {
    const lines = fs.readFileSync(path.join(planDir, file), 'utf8').split(/\r?\n/);
    let epic = null;
    let story = null;
    let task = null;
    for (const line of lines) {
      let m;
      if ((m = line.match(EPIC_RE))) {
        epic = { id: m[1], title: m[2].trim(), file, stories: [] };
        epics.push(epic);
      } else if ((m = line.match(STORY_RE))) {
        story = { id: m[1], title: m[2].trim(), tasks: [] };
        epic?.stories.push(story);
        task = null;
      } else if ((m = line.match(TASK_RE))) {
        task = { id: m[1], title: m[2].trim(), depends: [] };
        story?.tasks.push(task);
      } else if (task && /^Depends:/.test(line)) {
        const rest = line.replace(/^Depends:\s*/, '').trim();
        if (rest && !/^none/i.test(rest)) {
          task.depends = rest.split(/[,;]/).flatMap(parseDependency).filter(Boolean);
        }
      }
    }
  }
  return epics;
}

// "E4-S1..S8" -> [E4-S1, ..., E4-S8]; "E11 complete" -> [E11]; "B0 (for capabilities)" -> [B0]
function parseDependency(item) {
  const range = item.match(/((?:E|B)\d+)-S(\d+)\.\.S(\d+)/);
  if (range) {
    const out = [];
    for (let i = Number(range[2]); i <= Number(range[3]); i++) out.push(`${range[1]}-S${i}`);
    return out;
  }
  const m = item.match(/(?:E|B)\d+(?:-S\d+(?:-T\d+)?)?/);
  return m ? [m[0]] : [];
}

function sortByEpic(a, b) {
  const pa = a.match(/^(E|B)(\d+)/);
  const pb = b.match(/^(E|B)(\d+)/);
  if (pa[1] !== pb[1]) return pa[1] === 'E' ? -1 : 1;
  return Number(pa[2]) - Number(pb[2]);
}

function readStatus() {
  const state = new Map();
  if (!fs.existsSync(statusFile)) return state;
  for (const line of fs.readFileSync(statusFile, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^- \[( |x)\] `((?:E|B)\d+-S\d+-T\d+)`.*?(?:—\s*(.*))?$/);
    if (!m) continue;
    const note = (m[3] ?? '').trim();
    state.set(m[2], { done: m[1] === 'x', blocked: /^BLOCKED/.test(note), note });
  }
  return state;
}

function allTasks(epics) {
  return epics.flatMap((e) => e.stories.flatMap((s) => s.tasks.map((t) => ({ ...t, epic: e.id, story: s.id }))));
}

function isDone(dep, tasks, state) {
  const matching = tasks.filter((t) => t.id === dep || t.story === dep || t.epic === dep);
  if (matching.length === 0) return false;
  return matching.every((t) => state.get(t.id)?.done);
}

function writeStatus(epics, state) {
  const out = [];
  out.push('# Status board');
  out.push('');
  out.push('Generated by `node scripts/harness/plan-status.mjs --sync` from the epic files. Tick a task with `--done <id> <commit>`; mark problems with `--blocked <id> "<why>"`. Only the checkbox, the hash and the note after `—` are yours; titles come from the epic files.');
  out.push('');
  for (const epic of epics) {
    const tasks = epic.stories.flatMap((s) => s.tasks);
    const done = tasks.filter((t) => state.get(t.id)?.done).length;
    out.push(`## ${epic.id} · ${epic.title} (${done}/${tasks.length})`);
    out.push('');
    for (const story of epic.stories) {
      out.push(`### ${story.id} ${story.title}`);
      for (const t of story.tasks) {
        const s = state.get(t.id) ?? { done: false, note: '' };
        const box = s.done ? 'x' : ' ';
        const note = s.note ? ` — ${s.note}` : '';
        out.push(`- [${box}] \`${t.id}\` ${t.title}${note}`);
      }
      out.push('');
    }
  }
  fs.writeFileSync(statusFile, out.join('\n'));
}

function main() {
  const epics = readEpics();
  const tasks = allTasks(epics);
  const state = readStatus();
  const [cmd, ...rest] = process.argv.slice(2);

  if (cmd === '--sync') {
    writeStatus(epics, state);
    console.log(`STATUS.md synced: ${tasks.length} tasks across ${epics.length} epics`);
    return;
  }
  if (cmd === '--done' || cmd === '--blocked') {
    const id = rest[0];
    if (!tasks.some((t) => t.id === id)) {
      console.error(`Unknown task ${id}`);
      process.exit(1);
    }
    const prev = state.get(id) ?? { done: false, note: '' };
    if (cmd === '--done') state.set(id, { done: true, blocked: false, note: rest[1] ? `commit ${rest[1]}` : prev.note });
    else state.set(id, { done: false, blocked: true, note: `BLOCKED: ${rest.slice(1).join(' ')}` });
    writeStatus(epics, state);
    console.log(`${id} ${cmd === '--done' ? 'done' : 'blocked'}`);
    return;
  }
  if (cmd === 'next') {
    const open = tasks.filter((t) => !state.get(t.id)?.done && !state.get(t.id)?.blocked);
    const ready = open.filter((t) => t.depends.every((d) => isDone(d, tasks, state)));
    if (ready.length === 0) {
      console.log('No ready task. Open tasks with unmet dependencies:');
      for (const t of open.slice(0, 10)) console.log(`  ${t.id} ${t.title}  (needs ${t.depends.join(', ') || 'nothing'})`);
      return;
    }
    console.log('Ready tasks (dependencies done), in plan order:');
    for (const t of ready.slice(0, 15)) console.log(`  ${t.id}  ${t.title}  [${t.epic}]`);
    return;
  }
  if (cmd && /^(E|B)\d+$/.test(cmd)) {
    const epic = epics.find((e) => e.id === cmd);
    if (!epic) {
      console.error(`Unknown epic ${cmd}`);
      process.exit(1);
    }
    console.log(`${epic.id} · ${epic.title} (${epic.file})`);
    for (const story of epic.stories) {
      console.log(`  ${story.id} ${story.title}`);
      for (const t of story.tasks) {
        const s = state.get(t.id);
        const mark = s?.done ? 'done   ' : s?.blocked ? 'BLOCKED' : t.depends.every((d) => isDone(d, tasks, state)) ? 'ready  ' : 'waiting';
        console.log(`    [${mark}] ${t.id} ${t.title}${t.depends.length ? `  (depends ${t.depends.join(', ')})` : ''}`);
      }
    }
    return;
  }
  // summary
  for (const epic of epics) {
    const ts = epic.stories.flatMap((s) => s.tasks);
    const done = ts.filter((t) => state.get(t.id)?.done).length;
    const blocked = ts.filter((t) => state.get(t.id)?.blocked).length;
    console.log(`${epic.id.padEnd(4)} ${String(done).padStart(2)}/${String(ts.length).padEnd(3)} ${blocked ? `${blocked} blocked  ` : '           '} ${epic.title}`);
  }
  console.log(`\n${tasks.filter((t) => state.get(t.id)?.done).length}/${tasks.length} tasks done. Run with "next" for ready tasks.`);
}

main();
